- name: Enviar Alerta para o Discord
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "🚨 **ERRO NO DEPLOY!**\nO workflow do repositório ${{ github.repository }} falhou. Verifique os logs agora!"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
